#ifndef TYPE_SEX_HPP
#define TYPE_SEX_HPP 

const enum class type_sex {
	Agender,
	Androgyne,
	Androgynous,
	Bigender,
	Cis,
	Cisgender,
	Cis_Female,
	Cis_Male,
	Cis_Man,
	Cis_Woman,
	Cisgender_Female,
	Female,
	Female_to_Male,
	FTM,
	Gender_Fluid,
	Gender_Nonconforming,
	Gender_Questioning,
	Gender_Variant,
	Genderqueer,
	Intersex,
	Male,
	Male_to_Female,
	MTF,
	Neither,
	Neutrois,
	Non_binary,
	Other,
	Pangender,
	Trans,
	Trans_Female,
	Trans_Male,
	Trans_Man,
	Trans_Person,
	Trans_Woman,
	Transfeminine,
	Transgender,
	Transgender_Female,
	Transgender_Male,
	Transgender_Man,
	Transgender_Person,
	Transgender_Woman,
	Transmasculine,
	Transsexual,
	Transsexual_Female,
	Transsexual_Male,
	Transsexual_Man,
	Transsexual_Person,
	Transsexual_Woman,
	Two_Spirit
};

#endif /* TYPE_SEX_HPP */