name: university-db

on: [push]

jobs:
  Compile and run tests:
    runs-on: ubuntu-latest
    env:
      path: build
    steps:
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ctest -V